### ISSUE TITLE
Erro ao rodar imagem

### ISSUE THREAD

**Issue by henmohr** [MoinhoDigital/community-portal#19]
Após o build, não consigo rodar a imagem.

docker run portal
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module '/usr/src/app/index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Diretório /usr/src/app existe

# ls -lha /usr/src/app
total 8.0K
drwxr-xr-x 2 root root 4.0K May 23 09:44 .
drwxr-xr-x 3 root root 4.0K May 23 09:44 ..

Conteúdo do .env

SITE_NAME="Nome do site"
SITE_DESCRIPTION="Descrição do site"
TILE_SERVER="http://localhost:3000"
INTRANET=false
MAP_MIN_ZOOM=15
MAP_MAX_ZOOM=19
MAP_CENTER="-47.465106, -14.065287"
MAP_MIN_LONG_LAT="-47.48, -14.07"
MAP_MAX_LONG_LAT="-47.43, -14.04"

O que pode ser? D:

**Comment by luandro** [comment]
Atualizado, por favor testar @henmohr.

**Comment by henmohr** [comment]
Opa, muito bom o README @luandro !

Quando rodo a imagem com o comando docker run, o que aparece é uma listagem do diretório:

![Screenshot from 2021-06-10 12-47-08](https://user-images.githubusercontent.com/21038820/121556165-064a6080-c9ea-11eb-97b4-bf05369a21e9.png)

![Screenshot from 2021-06-10 12-47-44](https://user-images.githubusercontent.com/21038820/121556211-12362280-c9ea-11eb-91c2-d90b6af26764.png)

**Comment by henmohr** [comment]
Erro nas versões dos pacotes do VUE
$ npm run dev

> dev
> gridsome develop

Gridsome v0.7.18

Initializing plugins...
Error: 

Vue packages version mismatch:

- vue@2.6.14 (/home/dti/docker/community-portal/node_modules/vue/dist/vue.runtime.common.js)
- vue-template-compiler@2.6.11 (/home/dti/docker/community-portal/node_modules/vue-template-compiler/package.json)

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.

    at Object.<anonymous> (/home/dti/docker/community-portal/node_modules/vue-template-compiler/index.js:10:9)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:816:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (/home/dti/docker/community-portal/node_modules/gridsome/lib/plugins/vue-components/index.js:2:18)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:816:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Plugins.initialize (/home/dti/docker/community-portal/node_modules/gridsome/lib/app/Plugins.js:45:11)
    at App.init (/home/dti/docker/community-portal/node_modules/gridsome/lib/app/App.js:120:18)


Como corrigir?

**Comment by luandro** [comment]
@henmohr estamos agora focados no: https://gitlab.com/coletivo-coolab/portal-nuxt

Vê se funciona melhor pra vc.
